### ISSUE TITLE
Symlink resolution not robust or portable

### ISSUE THREAD

**Issue by cdlm** [ThierryGoubier/GitFileTree-MergeDriver#8]
I had a symlink to the `merge` script installed in my path (`~/bin/git-filetree-mergedriver`).
Git config using this name without an explicit path.

Symlink resolution fails at locating the command, so it looks for the MergeDriver VM and image in my project directory:
```
/Users/damien/bin/git-filetree-mergedriver: line 5: cd: ../.pharo/GitFileTree-MergeDriver: No such file or directory
/Users/damien/bin/git-filetree-mergedriver: line 7: cd: OLDPWD not set
/Users/damien/bin/git-filetree-mergedriver: line 11: /Users/damien/Documents/Pharo/filetree/filetree/pharo/pharo: No such file or directory
```

**Comment by ThierryGoubier** [comment]
The merge script has commands supposed to deal with the symlink, but they fail :(

I guess you're on a Mac?

**Comment by ThierryGoubier** [comment]
Yikes: it's supposed to be readlink -e or readlink -f, not readlink...

**Comment by ThierryGoubier** [comment]
Solved with 9199f62

**Comment by cdlm** [comment]
On mac, yes. `readlink` seems to be a pain to use in a portable way…

**Comment by ThierryGoubier** [comment]
Le 26 avr. 2015 14:54, "Damien Pollet" <notifications@github.com> a écrit :
>
> On mac, yes. readlink seems to be a pain to use in a portable way...

Well, the original code wasn't working under Linux... Can you check the new
merge works on your Mac?

Thierry
